name: Build and Push Docker Image to Azure Container Registry

on:
 push:
   branches:
     - main
 workflow_dispatch:

jobs:
 build-and-push:
   runs-on: ubuntu-latest
   permissions:
      id-token: write
   steps:
     - uses: actions/checkout@v4
     
     - name: 'Build and push image'
       uses: azure/docker-login@v1
       with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
     
     - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/exopek-webshop:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/exopek-webshop:latest

     - name: 'Azure Login'
       uses: azure/login@v1
       with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

     - name: 'Deploy to Azure Container App'
       uses: 'azure/webapps-deploy@v2'
       with:
          app-name: ${{ secrets.CONTAINER_APP_NAME }}
          images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/exopek-webshop:latest