name: Build and Push Docker Image to Azure Container Registry

on:
 push:
   branches:
     - main
 workflow_dispatch:

jobs:
 build-and-push:
   runs-on: ubuntu-latest
   permissions:
      id-token: write
   steps:
     - uses: actions/checkout@v4
     
     - name: 'Build and push image'
       uses: azure/docker-login@v1
       with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
     
     - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/exopek-shop:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/exopek-shop:latest

     - name: Build the frontend image and push it to ACR
       uses: docker/build-push-action@v5
       with:
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/exopek-webshop:latest
          file: dockerfile