name: Build and Push Docker Image to Azure Container Registry

on:
 push:
   branches:
     - main
 workflow_dispatch:

jobs:
 build-and-push:
   runs-on: ubuntu-latest
   permissions:
      id-token: write
   steps:
     - uses: actions/checkout@v4
     
     - name: 'Azure CLI login'
       uses: azure/login@v1
       with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7C2BE4472965433E8F1820312A4A4CF6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8B797D8D53C944E5BD77449D119307BA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_64176EAD91F14020BADB93F18249DAF3 }}
     
     - name: 'Build and push image'
       uses: azure/docker-login@v1
       with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
     
     - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/exopek-shop:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/exopek-shop:latest